### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by popoption** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#10]
I'm on 10.14.6 and I'm getting an error on the final step.
This is what I'm getting
------------------------
File "fetcher.py", line 38
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax
----------------------------

**Comment by bunnykek** [comment]
that should be
`def __init__(self) -> None:`
Better clone again the whole repo.
