### ISSUE TITLE
not working:(

### ISSUE THREAD

**Issue by larmarisss** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#12]
Hi I'm new here, i don't know this stuff but i'm getting this error

Checking if the static token is still alive...
Token expired!
Updating the token...
Token updated!
+----+------------+------------+-------+-------+
| ID | Resolution |  Bitrate   | Codec |  FPS  |
+----+------------+------------+-------+-------+
| 1  |  664x886   | 1.97 Mb/s  |  hvc1 | 29.97 |
| 2  |  310x414   | 0.27 Mb/s  |  avc1 | 29.97 |
| 3  |  352x470   | 0.38 Mb/s  |  avc1 | 29.97 |
| 4  |  394x526   | 0.53 Mb/s  |  avc1 | 29.97 |
| 5  |  436x582   |  0.8 Mb/s  |  avc1 | 29.97 |
| 7  |  486x648   | 1.65 Mb/s  |  avc1 | 29.97 |
| 8  |  830x1106  | 3.07 Mb/s  |  avc1 | 29.97 |
| 9  |  830x1108  | 4.24 Mb/s  |  avc1 | 29.97 |
| 12 | 1078x1438  | 6.78 Mb/s  |  avc1 | 29.97 |
| 13 | 1080x1440  | 9.76 Mb/s  |  avc1 | 29.97 |
| 14 |  310x414   | 0.33 Mb/s  |  hvc1 | 29.97 |
| 15 |  394x526   | 0.53 Mb/s  |  hvc1 | 29.97 |
| 16 |  436x582   | 0.75 Mb/s  |  hvc1 | 29.97 |
| 18 |  486x648   |  1.4 Mb/s  |  hvc1 | 29.97 |
| 19 |  830x1106  | 2.66 Mb/s  |  hvc1 | 29.97 |
| 20 |  830x1108  | 3.35 Mb/s  |  hvc1 | 29.97 |
| 23 | 1078x1438  | 6.06 Mb/s  |  hvc1 | 29.97 |
| 24 | 1080x1440  | 8.49 Mb/s  |  hvc1 | 29.97 |
| 25 | 1662x2216  | 14.9 Mb/s  |  hvc1 | 29.97 |
| 28 | 2048x2732  | 25.46 Mb/s |  hvc1 | 29.97 |
+----+------------+------------+-------+-------+
Enter the ID: 9

Downloading the video...
Traceback (most recent call last):
  File "/Users/larmarisssx/Desktop/Apple-Music-Animated-Artwork-Fetcher/fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "/Users/larmarisssx/Desktop/Apple-Music-Animated-Artwork-Fetcher/fetcher.py", line 68, in album
    self.processVideo(m3u8_, rep)
  File "/Users/larmarisssx/Desktop/Apple-Music-Animated-Artwork-Fetcher/fetcher.py", line 167, in processVideo
    subprocess.Popen(['ffmpeg', '-loglevel', 'quiet',
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by bunnykek** [comment]
Download the ffmpeg binary(.exe for Windows) for your OS from [here](https://ffbinaries.com/downloads) and put that binary inside Apple-Music-Animated-Artwork-Fetcher folder

**Comment by ZachWhittle** [comment]
You have to extract the .zip file, this gave me some confusion as well.
