### ISSUE TITLE
Requirments not installing...

### ISSUE THREAD

**Issue by Thonamy1** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#14]
I wanted to know what is happening and why i have this error

pip : El término 'pip' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable.
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e
inténtelo de nuevo.
En línea: 1 Carácter: 1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(Sorry i have the computer in spanish)

**Comment by bunnykek** [comment]
Reinstall python 3 in your system
