### ISSUE TITLE
No colorama

### ISSUE THREAD

**Issue by TheRealMarieRose** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#3]
ModuleNotFoundError: No module named 'colorama'

after py fetcher.py -A https://beta.music.apple.com/de/album/i-love-ep/1645995261

**Comment by TheRealMarieRose** [comment]
Yes, also after downloading it

**Comment by bunnykek** [comment]
> Yes, also after downloading it

Lel do 
`py -m pip install colorama`
