### ISSUE TITLE
Downloading Animated Artistbanner

### ISSUE THREAD

**Issue by ViPiMP** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#5]
Heyy, it would be great and helpful if it would be possible to download the animated  banner on the top of the Apple Music artist pages. Maybe it's possible some way. I wish you all the best!

Best Regards!

**Comment by bunnykek** [comment]
Yeah, its possible probably. Will implement it soon.

**Comment by ViPiMP** [comment]
> Yeah, its possible probably. Will implement it soon.

Yeah, I also kinda found out now. 
But I just fetched it from the Apple Music Beta Web Player. I got it in 1080p. If you could get it in better resolution let me please know! 

Greetings!

**Comment by bunnykek** [comment]
Check now. Updated the script.
Also yeah it can grab 4K hevc
\

**Comment by ViPiMP** [comment]
Thank you so f****** much!
Love yaa! <3
