### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by jasontkenny** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#7]
C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
Traceback (most recent call last):
  File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by jasontkenny** [comment]
C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
Traceback (most recent call last):
  File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 7, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

**Comment by bunnykek** [comment]
> C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
> Traceback (most recent call last):
>   File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'

`pip install -r requirements.txt`

**Comment by jasontkenny** [comment]
> > C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
> > Traceback (most recent call last):
> > File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in 
> > import requests
> > ModuleNotFoundError: No module named 'requests'
> 
> `pip install -r requirements.txt`

py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234

**Comment by jasontkenny** [comment]
> > C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
> > Traceback (most recent call last):
> > File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in 
> > import requests
> > ModuleNotFoundError: No module named 'requests'
> 
> `pip install -r requirements.txt`

same issue

**Comment by jasontkenny** [comment]
here's the full code, but i don't think i'm doing anything wrong

`Microsoft Windows [Version 10.0.22000.1455]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Owner>git clone https://github.com/bunnykek/Apple-Music-Animated-Artwork-Fetcher
Cloning into 'Apple-Music-Animated-Artwork-Fetcher'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 111 (delta 46), reused 17 (delta 9), pack-reused 0
Receiving objects:  98% (109/111), 2.40 MiB | 531.00 KiB/s
Receiving objects: 100% (111/111), 2.64 MiB | 553.00 KiB/s, done.
Resolving deltas: 100% (46/46), done.

C:\Users\Owner>cd Apple-Music-Animated-Artwork-Fetcher

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 1)) (2.28.2)
Requirement already satisfied: m3u8 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: mutagen in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 3)) (1.46.0)
Requirement already satisfied: colorama in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: prettytable in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: sanitize-filename in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: ffmpeg-python in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 7)) (0.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: iso8601 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from m3u8->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: wcwidth in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from prettytable->-r requirements.txt (line 5)) (0.2.6)
Requirement already satisfied: future in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ffmpeg-python->-r requirements.txt (line 7)) (0.18.3)

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>python fetcher.py -h

             /$$$$$$$$          /$$               /$$
            | $$_____/         | $$              | $$
            | $$     /$$$$$$  /$$$$$$    /$$$$$$$| $$$$$$$   /$$$$$$   /$$$$$$
            | $$$$$ /$$__  $$|_  $$_/   /$$_____/| $$__  $$ /$$__  $$ /$$__  $$
            | $$__/| $$$$$$$$  | $$    | $$      | $$  \ $$| $$$$$$$$| $$  \__/
            | $$   | $$_____/  | $$ /$$| $$      | $$  | $$| $$_____/| $$
            | $$   |  $$$$$$$  |  $$$$/|  $$$$$$$| $$  | $$|  $$$$$$$| $$
            |__/    \_______/   \___/   \_______/|__/  |__/ \_______/|__/
                    Apple-Music animated cover artwork downloader
                                                                -- by bunny

usage: fetcher.py [-h] [-T TYPE] [-L LOOPS] [-A] url

Downloads animated cover artwork from Apple music.

positional arguments:
  url                   Album/Playlist/Artist URL

options:
  -h, --help            show this help message and exit
  -T TYPE, --type TYPE  [tall,square] (tall/rectangle by default)
  -L LOOPS, --loops LOOPS
                        [int] Number of times you want to loop the artwork (No loops by default)
  -A, --audio           Pass this flag if you also need the audio

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
Traceback (most recent call last):
  File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>`

**Comment by bunnykek** [comment]
do
`python -m pip install -r requirements.txt`

**Comment by jasontkenny** [comment]
> do `python -m pip install -r requirements.txt`

`C:\Users\Owner>cd Apple-Music-Animated-Artwork-Fetcher

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>python -m pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 1)) (2.28.2)
Requirement already satisfied: m3u8 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: mutagen in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 3)) (1.46.0)
Requirement already satisfied: colorama in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: prettytable in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: sanitize-filename in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: ffmpeg-python in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 7)) (0.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: iso8601 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from m3u8->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: wcwidth in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from prettytable->-r requirements.txt (line 5)) (0.2.6)
Requirement already satisfied: future in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ffmpeg-python->-r requirements.txt (line 7)) (0.18.3)

C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher>py fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234
Traceback (most recent call last):
  File "C:\Users\Owner\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by bunnykek** [comment]
Just google search it. I did my best.
Its some module error from your side.
